before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bc
  - npm -g install jslint

language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10

branches:
  only:
    - master
    - future
